apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: frontend
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: graphtuitous
  name: frontend
  namespace: jduimovich
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: frontend
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:jduimovich-frontend
        imagePullPolicy: Always
        name: container-image
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
status: {}
