apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fib-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fib-go
    app.kubernetes.io/part-of: graphtuitous
  name: fib-go
  namespace: jduimovich
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: fib-go
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: fib-go
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:jduimovich-fib-go
        imagePullPolicy: Always
        name: container-image
        resources:
          requests:
            cpu: 200m
            memory: 64Mi
status: {}
